name: App code style workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./config
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r ../requirements/develop.txt

    - name: Isort
      run: isort .

    - name: Test with flake8
      run: flake8

    - name: Test with black
      run: black .
